version: '3.8'

services:
  # 1. DATABASE
  db:
    image: postgres:15
    container_name: hotel_db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root   # <-- Giữ 'root' cho đơn giản (hoặc đổi đồng bộ cả 2 nơi)
      POSTGRES_DB: hotel_management
    volumes:
      - pgdata:/var/lib/postgresql/data
      - ./backend/hotel_management.sql:/docker-entrypoint-initdb.d/init.sql

  # 2. BACKEND
  backend:
    build: ./backend
    container_name: hotel_backend
    restart: always
    ports:
      - "3000:3000"
    environment:
      - DB_HOST=db                # <-- QUAN TRỌNG: Phải là 'db', không được là 'localhost'
      - DB_USER=postgres
      - DB_PASSWORD=root          # <-- Phải khớp với password của service 'db' ở trên
      - DB_DATABASE=hotel_management
      - DB_PORT=5432
      - PORT=3000
      
      # Cấu hình JWT
      - JWT_SECRET=secret_key_change_me_in_production
      - JWT_EXPIRE=24h

      # Cấu hình Email (Mới thêm)
      - EMAIL_SERVICE=gmail
      - EMAIL_USER=caothaikhangcrypto@gmail.com
      - EMAIL_PASS=prwbortnitaacihp
    depends_on:
      - db

  # 3. FRONTEND WEB
  frontend:
    build: ./frontend
    container_name: hotel_frontend
    restart: always
    ports:
      - "8080:8080"
    environment:
      - PORT=8080
    depends_on:
      - backend

volumes:
  pgdata: